### ISSUE TITLE
basic information about code

### ISSUE THREAD

**Issue by Adorablepet** [QizeYang/PAUL#8]
Thanks for you sharing codes.I have a question about code. In `patchnet.py`, `path_position` indicates whether the value of the initialization is related to the affine matrix. What are the requirements for this? And if it is divided into singular, how to define it?

**Comment by QizeYang** [comment]
Hi, I hope this [link](https://en.wikipedia.org/wiki/Affine_transformation) and this [figure](https://en.wikipedia.org/wiki/Affine_transformation#/media/File:2D_affine_transformation_matrix.svg) of Wikipedia would be helpful for you to understand the initialization of the affine transformation.  Please refer to the section of `Image transformation`

**Comment by Adorablepet** [comment]
@QizeYang take a first patch as an example
```
[[1, 0, 0], [0, 1/6, -5/6]] [[x], [y], [1]] = [[x], [(1/6)y - 5/6]]
```
What is this image conversion, crop? why should I turn this way, such conversion is not for the msmt17 data sets.Every patch is such an operation.Are you just an operation in space invariance?Still learning other operations during the model training process?Thanks.

**Comment by QizeYang** [comment]
In the initial stage, the localization network is initialized such that the feature map would be divided into M equal-sized horizontal stripes. After training, the output affine transformation parameters would change. It could learn other operation during training so that the final transformation may contain translation, scale, cropping, rotation, etc. Such operations are not specific to a dataset.

**Comment by Adorablepet** [comment]
@QizeYang thanks, I know.
